import { readFile } from 'node:fs/promises'
import assert from 'node:assert/strict'
import { test } from 'node:test'
import { PGlite } from '@electric-sql/pglite'

const ids = {
    admin: '00000000-0000-4000-8000-000000000001',
    userA: '00000000-0000-4000-8000-000000000002',
    userB: '00000000-0000-4000-8000-000000000003',
    admin2: '00000000-0000-4000-8000-000000000004'
}

const db = new PGlite()
await db.exec(`
create role anon nologin;
create role authenticated nologin;
create schema auth;
create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub', true), '')::uuid $$;
grant usage on schema public, auth to anon, authenticated;
grant execute on function auth.uid() to anon, authenticated;
create table auth.users(id uuid primary key, email text, created_at timestamptz not null default now());
create table public.profiles(id uuid primary key references auth.users(id) on delete cascade, email text, role text default 'user' check(role in ('user','admin')));
create table public.links(id bigint generated by default as identity primary key, user_id uuid references auth.users(id), user_email text, slug text not null unique, original_url text, created_at timestamptz default now());
create table public.settings(key text primary key, value jsonb);
alter table public.links enable row level security;
create policy own_read on public.links for select to authenticated using (auth.uid() = user_id);
create policy own_insert on public.links for insert to authenticated with check (auth.uid() = user_id);
create policy own_delete on public.links for delete to authenticated using (auth.uid() = user_id);
grant select, insert, update, delete on public.links, public.settings to authenticated;
grant usage on all sequences in schema public to authenticated;
-- Deliberately broad historical policies must not defeat new restrictive boundaries.
create policy historical_open on public.links for all to authenticated using (true) with check (true);
alter table public.settings enable row level security;
create policy historical_settings on public.settings for all to authenticated using (true) with check (true);
`)
const migration = await readFile(new URL('../supabase/migrations/202610070001_user_permissions.sql', import.meta.url), 'utf8')
await db.exec(migration)
await db.exec(migration)
await db.exec(`insert into auth.users(id,email) values ('${ids.admin}','admin@example.test'),('${ids.userA}','a@example.test'),('${ids.userB}','b@example.test'),('${ids.admin2}','admin2@example.test');
update profiles set role='admin' where id in ('${ids.admin}', '${ids.admin2}');
insert into links(user_id,user_email,slug,original_url) values ('${ids.userA}','a@example.test','a-link','https://example.test/a'),('${ids.userB}','b@example.test','b-link','https://example.test/b');`)

async function asUser(id, sql, params = []) {
    await db.exec(`set role authenticated; select set_config('request.jwt.claim.sub', '${id}', false);`)
    try { return await db.query(sql, params) }
    finally { await db.exec('reset role;') }
}
async function change(id, field, value, actor = ids.admin, expected) {
    const { rows } = await db.query('select updated_at::text from profiles where id=$1', [id])
    return asUser(actor, 'select admin_update_user($1,$2,$3,$4,$5)', [id, field, value, expected ?? rows[0].updated_at, 'test change'])
}

await test('profile trigger creates safe defaults and synchronizes email', async () => {
    const { rows } = await db.query('select role,status from profiles where id=$1', [ids.userA])
    assert.deepEqual(rows[0], { role: 'user', status: 'active' })
    await db.exec(`update auth.users set email='new-a@example.test' where id='${ids.userA}'`)
    assert.equal((await db.query('select email from profiles where id=$1', [ids.userA])).rows[0].email, 'new-a@example.test')
})
await test('ordinary users cannot list users, mutate profiles, or read other links', async () => {
    await assert.rejects(asUser(ids.userA, 'select admin_list_users()'), /FORBIDDEN/)
    await assert.rejects(change(ids.userB, 'role', 'admin', ids.userA), /FORBIDDEN/)
    await assert.rejects(asUser(ids.userA, "update profiles set role='admin' where id=$1", [ids.userA]), /permission denied/)
    assert.equal((await asUser(ids.userA, 'select * from links')).rows.length, 1)
    assert.equal((await asUser(ids.userA, 'delete from links where user_id=$1 returning id', [ids.userB])).rows.length, 0)
    await assert.rejects(asUser(ids.userA, "insert into links(user_id,slug) values ($1,'forged')", [ids.userB]), /row-level security/)
    await assert.rejects(asUser(ids.userA, "insert into settings(key,value) values ('hack','{}')"), /row-level security/)
})
await test('anonymous cannot invoke privileged RPCs or read profiles/audit', async () => {
    await db.exec('set role anon')
    try {
        await assert.rejects(db.query('select admin_list_users()'), /permission denied/)
        await assert.rejects(db.query('select * from profiles'), /permission denied/)
        await assert.rejects(db.query('select * from admin_audit_logs'), /permission denied/)
    } finally { await db.exec('reset role') }
})
await test('admin search, filtering, counts and pagination', async () => {
    const { rows } = await asUser(ids.admin, "select admin_list_users('new-a','user','active',1) as result")
    assert.equal(rows[0].result.total, 1)
    assert.equal(rows[0].result.users[0].link_count, 1)
    assert.equal(rows[0].result.users[0].id, ids.userA)
    await assert.rejects(asUser(ids.admin, "select admin_list_users('', 'admin', 'all', 0)"), /INVALID_INPUT/)
})
await test('role and status mutations are audited and stale writes rejected', async () => {
    const previous = (await db.query('select updated_at::text from profiles where id=$1', [ids.userB])).rows[0].updated_at
    await change(ids.userB, 'role', 'admin')
    await assert.rejects(change(ids.userB, 'role', 'user', ids.admin, previous), /STALE_USER/)
    await change(ids.userB, 'role', 'user')
    assert.equal((await db.query("select count(*)::int as n from admin_audit_logs where action='user.role'")).rows[0].n, 2)
    await assert.rejects(change(ids.userB, 'status', 'invalid'), /INVALID_INPUT/)
})
await test('disabled sessions lose all resource access but data is retained', async () => {
    await change(ids.userA, 'status', 'disabled')
    assert.equal((await asUser(ids.userA, 'select * from links')).rows.length, 0)
    await assert.rejects(asUser(ids.userA, "insert into links(user_id,slug) values ($1,'disabled')", [ids.userA]), /row-level security/)
    assert.equal((await db.query('select * from links where user_id=$1', [ids.userA])).rows.length, 1)
    await assert.rejects(asUser(ids.userA, 'select record_account_activity()'), /FORBIDDEN/)
    await change(ids.userA, 'status', 'active')
    await asUser(ids.userA, 'select record_account_activity()')
    assert.ok((await db.query('select last_seen_at from profiles where id=$1', [ids.userA])).rows[0].last_seen_at)
})
await test('last active administrator and self-suspension are protected', async () => {
    await change(ids.admin2, 'role', 'user')
    await assert.rejects(change(ids.admin, 'role', 'user'), /LAST_ADMIN/)
    await assert.rejects(change(ids.admin, 'status', 'disabled'), /LAST_ADMIN/)
    await change(ids.admin2, 'role', 'admin')
    await assert.rejects(change(ids.admin, 'status', 'disabled'), /SELF_DISABLE/)
})
await test('privileged deletions create audit entries without URLs', async () => {
    await asUser(ids.admin, 'delete from links where user_id=$1', [ids.userB])
    const row = (await db.query("select before_value from admin_audit_logs where action='link.delete'")).rows[0]
    assert.equal(row.before_value.slug, 'b-link')
    assert.equal(row.before_value.original_url, undefined)
    assert.equal((await asUser(ids.userA, 'select * from admin_audit_logs')).rows.length, 0)
})
await db.close()
